services:

  infra:
    path: infrastructure

  api:
    path: api
    dependsOn:
      - infra
    params:
      masterTableArn: ${infra.MasterTableArn}
      aiTableArn: ${infra.AITableArn}
      imagesBucketName: ${infra.ImagesS3BucketName}
      cognitoUserPoolId: ${infra.CognitoUserPoolId}

  frontend:
    path: frontend
    dependsOn:
      - api
    params:
      s3BucketName: ${infra.S3BucketName}
      apiGatewayUrl: ${api.ApiGatewayUrl}
      apiGatewayId: ${api.ApiGatewayRestApiId}
    inputs:
      alwaysDeploy: true
