services:

  infra:
    path: infrastructure

  api:
    path: api
    dependsOn:
      - infra
    params:
      masterTableArn: ${infra.MasterTableArn}
      aiTableArn: ${infra.AITableArn}
      imagesBucketName: ${infra.ImagesS3BucketName}
      cognitoUserPoolId: ${infra.CognitoUserPoolId}

