S3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.bucketName}
    WebsiteConfiguration:
      IndexDocument: index.html
      ErrorDocument: index.html
    PublicAccessBlockConfiguration:
      BlockPublicAcls: false
      BlockPublicPolicy: false
      IgnorePublicAcls: false
      RestrictPublicBuckets: false
    CorsConfiguration:
      CorsRules:
        - AllowedOrigins:
            - "*"
          AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - HEAD
          MaxAge: 3000

ImagesS3Bucket:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: ${self:custom.imagesBucket}
    PublicAccessBlockConfiguration:
      BlockPublicAcls: true
      BlockPublicPolicy: true
      IgnorePublicAcls: true
      RestrictPublicBuckets: true
    CorsConfiguration:
      CorsRules:
        - AllowedOrigins:
            - "*"
          AllowedHeaders:
            - "*"
          AllowedMethods:
            - GET
            - HEAD
            - PUT
            - POST
            - DELETE
          MaxAge: 3000

CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:service}-user-pool-${self:custom.stage}
    AutoVerifiedAttributes:
      - email
    UsernameAttributes:
      - email
    UsernameConfiguration:
      CaseSensitive: false
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: false
        TemporaryPasswordValidityDays: 7
    MfaConfiguration: "OFF"
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    UserPoolTags:
      Environment: ${self:custom.stage}
      Service: ${self:service}
    Schema:
      - Name: email
        AttributeDataType: String
        Required: true
        Mutable: true
      - Name: given_name
        AttributeDataType: String
        Required: false
        Mutable: true
      - Name: family_name
        AttributeDataType: String
        Required: false
        Mutable: true

CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:service}-client-${self:custom.stage}
    UserPoolId: !Ref CognitoUserPool
    GenerateSecret: false
    ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    SupportedIdentityProviders:
      - COGNITO
    CallbackURLs:
      - http://localhost:5001
      - https://${self:custom.bucketName}.s3-website-${self:provider.region}.amazonaws.com
    LogoutURLs:
      - http://localhost:5001
      - https://${self:custom.bucketName}.s3-website-${self:provider.region}.amazonaws.com
    AllowedOAuthFlows:
      - code
      - implicit
    AllowedOAuthScopes:
      - phone
      - email
      - openid
      - profile
    AllowedOAuthFlowsUserPoolClient: true
    RefreshTokenValidity: 30
    AccessTokenValidity: 1
    IdTokenValidity: 1
    TokenValidityUnits:
      AccessToken: hours
      IdToken: hours
      RefreshToken: days

CognitoIdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties:
    IdentityPoolName: ${self:service}_identity_pool_${self:custom.stage}
    AllowUnauthenticatedIdentities: false
    CognitoIdentityProviders:
      - ClientId: !Ref CognitoUserPoolClient
        ProviderName: !GetAtt CognitoUserPool.ProviderName

CognitoAuthRole:
  Type: AWS::IAM::Role
  Properties:
    RoleName: ${self:service}-auth-role-${self:custom.stage}
    AssumeRolePolicyDocument:
      Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Federated: cognito-identity.amazonaws.com
          Action: sts:AssumeRoleWithWebIdentity
          Condition:
            StringEquals:
              'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
            'ForAnyValue:StringLike':
              'cognito-identity.amazonaws.com:amr': authenticated
    Policies:
      - PolicyName: CognitoAuthPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource:
                - !Sub "arn:aws:s3:::${ImagesS3Bucket}/*"
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:Query
              Resource:
                - !GetAtt MasterTable.Arn
                - !Sub "${MasterTable.Arn}/index/*"
                - !GetAtt AITable.Arn
                - !Sub "${AITable.Arn}/index/*"

IdentityPoolRoleMapping:
  Type: AWS::Cognito::IdentityPoolRoleAttachment
  Properties:
    IdentityPoolId: !Ref CognitoIdentityPool
    Roles:
      authenticated: !GetAtt CognitoAuthRole.Arn

# Master Table - カメラマスタ（MACアドレス→カメラID変換）
MasterTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-master
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: mac_address
        AttributeType: S
      - AttributeName: plant_name
        AttributeType: S
      - AttributeName: equipment
        AttributeType: S
      - AttributeName: capture_date
        AttributeType: S
    KeySchema:
      - AttributeName: mac_address
        KeyType: HASH
    GlobalSecondaryIndexes:
      # プラント名称 + 日付検索用GSI
      - IndexName: PlantDateIndex
        KeySchema:
          - AttributeName: plant_name
            KeyType: HASH
          - AttributeName: capture_date
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
      # 機器 + 日付検索用GSI
      - IndexName: EquipmentDateIndex
        KeySchema:
          - AttributeName: equipment
            KeyType: HASH
          - AttributeName: capture_date
            KeyType: RANGE
        Projection:
          ProjectionType: ALL
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}

# AI Table - AI処理設定管理
AITable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-ai
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: camera_id
        AttributeType: S
    KeySchema:
      - AttributeName: camera_id
        KeyType: HASH
    StreamSpecification:
      StreamViewType: NEW_AND_OLD_IMAGES
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}

# UserPlantAccess Table - ユーザーがアクセス可能なプラント
# PK=user_id（Cognito sub推奨）, SK=plant_id
UserPlantAccessTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-user-plant
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: user_id
        AttributeType: S
      - AttributeName: plant_id
        AttributeType: S
    KeySchema:
      - AttributeName: user_id
        KeyType: HASH
      - AttributeName: plant_id
        KeyType: RANGE
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}

# Plants Table - プラントマスタ
# PK=plant_id
PlantsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-plants
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: plant_id
        AttributeType: S
    KeySchema:
      - AttributeName: plant_id
        KeyType: HASH
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}

# Devices Table - 計器マスタ
# PK=plant_id, SK=device_id
# Attributes:
#   - device_name (S)
#   - location (S)
#   - latest_value (N)
#   - latest_ts (S)
DevicesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-devices
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: plant_id
        AttributeType: S
      - AttributeName: device_id
        AttributeType: S
    KeySchema:
      - AttributeName: plant_id
        KeyType: HASH
      - AttributeName: device_id
        KeyType: RANGE
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}

# Readings Table - 読み値（計器単位の時系列）
# PK=device_id, SK=timestamp（ISO 8601 文字列推奨）
# Attributes:
#   - value (N)
#   - image_url (S)
ReadingsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.tableName}-readings
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: device_id
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: S
    KeySchema:
      - AttributeName: device_id
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    Tags:
      - Key: Environment
        Value: ${self:custom.stage}
      - Key: Service
        Value: ${self:service}
