# Cognito User Pool
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: ${self:service}-user-pool-${self:custom.stage}
    AutoVerifiedAttributes:
      - email
    UsernameAttributes:
      - email
    UsernameConfiguration:
      CaseSensitive: false
    Policies:
      PasswordPolicy:
        MinimumLength: 8
        RequireUppercase: true
        RequireLowercase: true
        RequireNumbers: true
        RequireSymbols: false
        TemporaryPasswordValidityDays: 7
    MfaConfiguration: "OFF"
    AccountRecoverySetting:
      RecoveryMechanisms:
        - Name: verified_email
          Priority: 1
    UserPoolTags:
      Environment: ${self:custom.stage}
      Service: ${self:service}
    Schema:
      - Name: email
        AttributeDataType: String
        Required: true
        Mutable: true
      - Name: given_name
        AttributeDataType: String
        Required: false
        Mutable: true
      - Name: family_name
        AttributeDataType: String
        Required: false
        Mutable: true

# Cognito User Pool Client
CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    ClientName: ${self:service}-client-${self:custom.stage}
    UserPoolId: !Ref CognitoUserPool
    GenerateSecret: false
    ExplicitAuthFlows:
      - ALLOW_USER_PASSWORD_AUTH
      - ALLOW_USER_SRP_AUTH
      - ALLOW_REFRESH_TOKEN_AUTH
    SupportedIdentityProviders:
      - COGNITO
    CallbackURLs:
      - http://localhost:5001
      - https://${self:custom.bucketName}.s3-website-${self:provider.region}.amazonaws.com
    LogoutURLs:
      - http://localhost:5001
      - https://${self:custom.bucketName}.s3-website-${self:provider.region}.amazonaws.com
    AllowedOAuthFlows:
      - code
      - implicit
    AllowedOAuthScopes:
      - phone
      - email
      - openid
      - profile
    AllowedOAuthFlowsUserPoolClient: true
    RefreshTokenValidity: 30
    AccessTokenValidity: 1
    IdTokenValidity: 1
    TokenValidityUnits:
      AccessTo
